>>> from exceptional import string_log
>>> string_log("ouch!".split())
Conversion error: KeyError('ouch!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abingham/repos/sixty-north/pluralsight/core-python-getting-started/resources/m08/visning/clip-05/use-string-log/exceptional.py", line 32, in string_log
    return log(v)
ValueError: math domain error

